import type { Metadata } from "next";
import "./globals.css";
import { ClientLayout, Loader } from '@/components';
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Techentia PDF Formatter",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={``} suppressHydrationWarning>
        <Suspense fallback={<Loader />}>
          <ClientLayout>{children}</ClientLayout>
        </Suspense>
      </body>
    </html>
  );
}
